### ISSUE TITLE
Updater not working

### ISSUE THREAD

**Issue by guiweber** [mattgwagner/Dreamhost-Dynamic-DNS-Updater#9]
The updater is not working for my domains and I'm not sure why. I created A records for 4 sub-domains I want to update and put them as CSV values in the app.config file, as well as my API key and my DH user name. When I start the update service the log shows the following information. There are no errors but it doesn't seem to complete its task:

```
2017-07-25 15:38:07.0835|INFO|DHDns.Service.Program+TaskService|Starting Dynamic DNS Update Service...
2017-07-25 15:38:07.1281|INFO|DHDns.Library.UpdateJob|Starting UpdateJob...
2017-07-25 15:38:07.5574|INFO|DHDns.Library.UpdateJob|Retrieved current IP: XXX.XXX.XXX.XXX
```

**Comment by mattgwagner** [comment]
To be honest, I moved my domains over to Google Domains a few years ago and don't have an active account with DH. If you figure out the issue, a PR would be greatly appreciated!

**Comment by guiweber** [comment]
Ok, will do! Is there any way to increase verbosity? Not much info shown in the log.

**Comment by guiweber** [comment]
Well, good news. I built a new version with much more debug info and without doing code changes, and it started working on its own : )

Maybe Dreamhost API was having network issues on their end... So it looks like the service still works as-is!

**Comment by mattgwagner** [comment]
Awesome, the best code changes are no changes.

RE: Logging, you can adjust the log levels via https://github.com/mattgwagner/Dreamhost-Dynamic-DNS-Updater/blob/master/Service/App.config#L21  but there probably could use more log verbose/debug entries in there in general.
